Repository timescale/promscale, pull requests merged in 2020-10, with the labels that each got.

#278 Fix max_connections setting in tests
  pkg/internal/testhelpers/containers.go
Labels: kind/testing

#300 Fix logging output to match rest of the project
  pkg/pgclient/client.go
  pkg/pgmodel/extension.go
  pkg/pgmodel/sql_ingest.go
Labels: kind/cleanup

#301 Fix erroneous PromQL query in end-to-end tests
  pkg/pgmodel/end_to_end_tests/promql_query_endpoint_test.go
Labels: kind/cleanup

#291 Add SQL API for managing metric compression setting
  pkg/pgmodel/end_to_end_tests/create_test.go
  pkg/pgmodel/migrations/migration_files_generated.go
  pkg/pgmodel/migrations/sql/idempotent/base.sql
  pkg/pgmodel/migrations/sql/preinstall/003-tables.sql
  pkg/pgmodel/migrations/sql/versions/dev/0.1.1-dev/1-add_default_compression_setting.sql
  pkg/version/version.go
Labels: kind/feature

#309 Add code documentation for query/read path of the connector
  pkg/pgmodel/labels.go
  pkg/pgmodel/querier.go
  pkg/pgmodel/sql_reader.go
Labels: kind/documentation

#316 BUGFIX reset pendingBuffer epoch when we're done
  pkg/pgmodel/sql_ingest.go
Labels: kind/bug

#315 Remove old mock
  pkg/pgmodel/sql_test.go
Labels: kind/cleanup
