Repository timescale/promscale, pull requests merged in 2020-09, with the labels that each got.

#258 Add text about compliance to Readme
  README.md
Labels: kind/documentation

#264 Ensure fate-sharing for the migration lock
  pkg/pgmodel/end_to_end_tests/main_test.go
  pkg/pgmodel/end_to_end_tests/migrate_test.go
  pkg/pgmodel/extension.go
  pkg/pgmodel/migrate.go
  pkg/pgmodel/upgrade_tests/upgrade_test.go
  pkg/runner/runner.go
  pkg/util/lock.go
Labels: kind/bug, priority/sev3, version/0.1.0

#266 Add log format flag and default to logfmt formatting for logs
  cmd/promscale/main.go
  pkg/api/common_test.go
  pkg/api/health_test.go
  pkg/api/labels_test.go
  pkg/api/query_range_test.go
  pkg/api/query_test.go
  pkg/api/series_test.go
  pkg/api/write_test.go
  pkg/log/log.go
  pkg/pgmodel/end_to_end_tests/main_test.go
  pkg/pgmodel/upgrade_tests/upgrade_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/util/election_test.go
  pkg/util/util_test.go
Labels: kind/cleanup
