Repository timescale/promscale, pull requests merged in 2021-12, with the labels that each got.

#939 Make prom-migrator unit test independent of current time
  cmd/prom-migrator/main.go
  cmd/prom-migrator/main_test.go
Labels: kind/testing

#935 helm: Simplifying enablement of otel tracing
  helm-chart/README.md
  helm-chart/templates/deployment-promscale.yaml
  helm-chart/templates/svc-promscale.yaml
  helm-chart/values.yaml
Labels: component/helm

#954 Add Make Target for Downloading Trace Dataset
  .gitignore
  Makefile
Labels: kind/testing

#960 Run full test suite on PG14
  .github/workflows/go.yml
  pkg/internal/testhelpers/postgres_container.go
  pkg/tests/end_to_end_tests/continuous_agg_test.go
  pkg/tests/end_to_end_tests/main_test.go
Labels: Test

#958 Fix _prom_catalog.metric_view() function on non-tsdb installs
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/base.sql
Labels: Bug

#956 Add tests for the operation_calls database function
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/tracing-functions.sql
  pkg/tests/end_to_end_tests/trace_operation_calls_test.go
  pkg/tests/end_to_end_tests/trace_tree_test.go
Labels: Test

#988 Fix hardcoded schema names in SQL
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/tracing-functions.sql
  pkg/migrations/sql/idempotent/tracing-tags.sql
Labels: Bug

#986 Change the default for `db-writer-connection-concurrency`
  docs/cli.md
  pkg/pgclient/config.go
Labels: Performance

#987 Add SQL based stats for Telemetry.
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/telemetry.sql
  pkg/telemetry/telemetry.go
  pkg/tests/end_to_end_tests/telemetry_test.go
Labels: Feature

#992 Adds support for PromQL based telemetry stats.
  pkg/api/metrics.go
  pkg/runner/runner.go
  pkg/telemetry/promql.go
  pkg/telemetry/telemetry.go
  pkg/tests/end_to_end_tests/migrate_test.go
  pkg/tests/end_to_end_tests/telemetry_test.go
Labels: Feature

#979 Remove the event_name_check constraint
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/preinstall/010-tracing.sql
  pkg/migrations/sql/versions/dev/0.7.2-dev/3-event_name.sql
  pkg/tests/upgrade_tests/shapshot.go
  pkg/version/version.go
Labels: Bug
