Repository timescale/promscale, pull requests merged in 2022-01, with the labels that each got.

#1008 Fix passing of async flag
  pkg/pgclient/client.go
  pkg/pgclient/config.go
  pkg/pgclient/config_test.go
  pkg/pgmodel/ingestor/ingestor.go
  pkg/runner/flags.go
Labels: Bug

#1011 Add `db-writer-connection-concurrency` flag back
  pkg/runner/flags.go
  pkg/runner/flags_test.go
Labels: Bug

#1013 Run `go generate` in Makefile and Dockerfile
  Makefile
  build/Dockerfile
Labels: Bug

#1012 Add the ability to delete trace data
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/tracing-functions.sql
  pkg/tests/end_to_end_tests/trace_delete_test.go
Labels: Feature

#1015 Add data retention policy for trace data
  docs/tracing.md
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/base.sql
  pkg/migrations/sql/idempotent/maintenance.sql
  pkg/migrations/sql/preinstall/004-tables.sql
  pkg/migrations/sql/versions/dev/0.7.2-dev/4-data_retention.sql
  pkg/pgmodel/migrate.go
  pkg/tests/end_to_end_tests/trace_delete_test.go
  pkg/tests/end_to_end_tests/trace_retention_test.go
  pkg/version/version.go
Labels: Feature

#1032 Add telemetry CLI flag section
  docs/cli.md
  pkg/log/log.go
  pkg/runner/flags.go
Labels: Improvement

#1046 Remove unnecessary locking in `get_or_create_series_id_for_label_array`
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/base.sql
Labels: Performance

#1053 Rename span_retention_period
  CHANGELOG.md
  docs/sql_api.md
  docs/tracing.md
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/maintenance.sql
  pkg/migrations/sql/preinstall/004-tables.sql
  pkg/migrations/sql/versions/dev/0.7.2-dev/4-data_retention.sql
  pkg/tests/end_to_end_tests/trace_retention_test.go
Labels: Feature

#1081 Fix skipping compression of first to last chunk
  CHANGELOG.md
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/base.sql
  pkg/tests/end_to_end_tests/create_test.go
Labels: Improvement

#1062 Cache metric ID and forward the metric info to series writer
  CHANGELOG.md
  pkg/migrations/migration_files_generated.go
  pkg/migrations/sql/idempotent/base.sql
  pkg/migrations/sql/versions/dev/0.8.1-dev/1-drop_old_series_funcs.sql
  pkg/pgmodel/ingestor/copier.go
  pkg/pgmodel/ingestor/exemplar_label_formatter.go
  pkg/pgmodel/ingestor/ingestor_sql_test.go
  pkg/pgmodel/ingestor/metric_batcher.go
  pkg/pgmodel/ingestor/metric_batcher_test.go
  pkg/pgmodel/ingestor/series_writer.go
  pkg/pgmodel/model/metric.go
  pkg/pgmodel/model/series.go
  pkg/tests/end_to_end_tests/sql_bench_test.go
  pkg/version/version.go
Labels: Performance
