Repository timescale/promscale, pull requests merged in 2022-09, with the labels that each got.

#1615 Run timescaledb-tune with the promscale profile
  CHANGELOG.md
  docker-compose/docker-compose.yaml
Labels: Documentation

#1603 Fix broken cache eviction in clockcache
  CHANGELOG.md
  pkg/clockcache/cache.go
  pkg/clockcache/cache_test.go
Labels: action:benchmarks

#1651 Bump jaeger to 1.38.0
  go.mod
  go.sum
  pkg/jaeger/api.go
Labels: epic/jaeger-grpc-write

#1657 Add a database connection pool for maintenance jobs
  CHANGELOG.md
  docs/configuration.md
  pkg/pgclient/client.go
  pkg/pgclient/config.go
  pkg/pgclient/config_test.go
  pkg/pgclient/metrics.go
  pkg/runner/runner.go
  pkg/tests/end_to_end_tests/alerts_test.go
  pkg/tests/end_to_end_tests/migrate_test.go
  pkg/tests/end_to_end_tests/multi_tenancy_test.go
  pkg/tests/end_to_end_tests/promql_endpoint_integration_test.go
  pkg/tests/end_to_end_tests/rules_test.go
  pkg/tests/end_to_end_tests/telemetry_test.go
Labels: epic/autovacuum-improvements

#1665 Wrap extension upgrades in a transaction
  CHANGELOG.md
  pkg/pgmodel/new_migrate.go
Labels: Bug

#1661 Metrics for long-running statements and locks originating from maintenance jobs
  CHANGELOG.md
  docs/mixin/dashboards/promscale.json
  pkg/pgmodel/metrics/database/metrics.go
  pkg/util/metrics.go
Labels: epic/maintenance-job-o11y

#1679 Reuse ingestion temp tables across batches
  CHANGELOG.md
  pkg/pgmodel/ingestor/copier.go
  pkg/pgmodel/ingestor/ingestor_sql_test.go
Labels: Improvement
