Repository timescale/promscale, pull requests merged in 2022-08, with the labels that each got.

#1555 Use test table in Trace Ingestion tests
  pkg/tests/end_to_end_tests/ingest_trace_test.go
Labels: Refactor

#1534 Add benchmark to test varying ingestion load
  pkg/tests/end_to_end_tests/metric_ingest_bench_test.go
  pkg/tests/testsupport/series_gen.go
Labels: action:benchmarks

#1554 Add batching for traces
  CHANGELOG.md
  docs/configuration.md
  pkg/jaeger/store/store.go
  pkg/pgclient/client.go
  pkg/pgclient/config.go
  pkg/pgmodel/ingestor/dispatcher.go
  pkg/pgmodel/ingestor/ingestor.go
  pkg/pgmodel/ingestor/ingestor_sql_test.go
  pkg/pgmodel/ingestor/trace/tag_batch_test.go
  pkg/pgmodel/ingestor/trace/trace_batcher.go
  pkg/pgmodel/ingestor/trace/trace_batcher_test.go
  pkg/pgmodel/ingestor/trace/trace_dispatcher.go
  pkg/pgmodel/ingestor/trace/writer.go
  pkg/pgmodel/metrics/ingest.go
  pkg/runner/runner.go
  pkg/tests/end_to_end_tests/database_metrics_test.go
  pkg/tests/end_to_end_tests/datasets_metrics_test.go
  pkg/tests/end_to_end_tests/drop_test.go
  pkg/tests/end_to_end_tests/ha_single_promscale_test.go
  pkg/tests/end_to_end_tests/ingest_bench_test.go
  pkg/tests/end_to_end_tests/ingest_trace_test.go
  pkg/tests/end_to_end_tests/insert_compressed_chunks_test.go
  pkg/tests/end_to_end_tests/jaeger_store_test.go
  pkg/tests/end_to_end_tests/trace_ingest_bench_test.go
  pkg/tests/end_to_end_tests/trace_query_integration_test.go
  pkg/tests/testdata/trace_data.go
  pkg/tracer/trace.go
  scripts/end_to_end_tests.sh
Labels: epic/jaeger-grpc-write

#1588 Rename CLI flag to control GRPC server used for Jaeger and OTEL traces
  CHANGELOG.md
  docs/configuration.md
  pkg/runner/flags.go
  pkg/runner/flags_test.go
  pkg/runner/runner.go
Labels: epic/jaeger-grpc-write
