Repository timescale/promscale, pull requests merged in 2022-11, with the labels that each got.

#1745 More maintenance jobs metrics
  CHANGELOG.md
  docs/mixin/dashboards/promscale.json
  pkg/pgmodel/metrics/database/database.go
  pkg/pgmodel/metrics/database/metrics.go
  pkg/tests/end_to_end_tests/create_test.go
  pkg/tests/end_to_end_tests/database_metrics_test.go
  pkg/util/metrics.go
  pkg/util/util_test.go
Labels: epic/maintenance-job-o11y

#1740 Add the troubleshooting guide
  docs/runbooks/troubleshooting-guide.md
Labels: epic/improved-cloud-supportability

#1755 Add prometheus metrics to vacuum engine
  pkg/vacuum/vacuum.go
Labels: Improvement

#1768 Removing 16 bytes alignment for cache elements
  pkg/clockcache/cache.go
  pkg/clockcache/cache_bench_test.go
  pkg/clockcache/cache_test.go
Labels: Performance, epic/out-of-the-box
