Repository timescale/promscale, pull requests merged in 2022-02, with the labels that each got.

#1095 Fix metric info cache loading when using query path
  pkg/pgmodel/querier/common.go
  pkg/pgmodel/querier/querier_sql_test.go
  pkg/pgmodel/querier/query_tools.go
  scripts/end_to_end_tests.sh
Labels: Performance

#1100 add Promscale logo
  README.md
  images/promscale-logo.png
Labels: Documentation

#1096 Ensure that span start <= end
  CHANGELOG.md
  pkg/pgmodel/ingestor/trace/writer.go
  pkg/tests/end_to_end_tests/dataset_traces_test.go
Labels: Bug

#1139 Don't log success message if extension update failed
  pkg/pgmodel/common/extension/extension.go
Labels: Bug

#1152 Increase visibility into trace ingest
  pkg/api/write.go
  pkg/api/write_test.go
  pkg/pgmodel/ingestor/trace/batch.go
  pkg/pgmodel/ingestor/trace/writer.go
  pkg/pgmodel/metrics/ingest.go
  pkg/pgmodel/model/sql_test_utils.go
  pkg/pgxconn/pgx_conn.go
Labels: Improvement

#1179 Upgrade PGX to latest master
  go.mod
  go.sum
Labels: Bug
