Repository timescale/promscale, pull requests merged in 2022-12, with the labels that each got.

#1775 Adds support to instrument metric-rollups behaviour
  pkg/pgmodel/metrics/database/database.go
  pkg/pgmodel/metrics/database/metric_series.go
  pkg/pgmodel/metrics/database/metrics.go
Labels: epic/auto-rollups

#1776 Update rollups creation/deletion/updation using dataset-config
  pkg/dataset/config.go
  pkg/dataset/downsample.go
  pkg/rollup/config.go
  pkg/rollup/rollup.go
  pkg/rollup/rollup_test.go
  pkg/runner/client.go
  pkg/tests/end_to_end_tests/config_dataset_test.go
  pkg/tests/end_to_end_tests/rollup_test.go
Labels: epic/auto-rollups

#1786 Bump series cache default size
  pkg/pgmodel/cache/series_cache.go
Labels: epic/better-defaults, epic/out-of-the-box

#1785 Cache invalidation interleaving test
  pkg/tests/end_to_end_tests/create_test.go
Labels: epic/cache-invalidation

#1795 Grow inverted labels cache if needed
  pkg/pgclient/client.go
  pkg/pgmodel/cache/cache.go
  pkg/pgmodel/cache/flags.go
  pkg/pgmodel/cache/inverted_labels_cache.go
  pkg/pgmodel/cache/series_cache.go
  pkg/pgmodel/cache/series_cache_test.go
  pkg/pgmodel/ingestor/dispatcher.go
  pkg/pgmodel/ingestor/ingestor.go
  pkg/pgmodel/ingestor/ingestor_sql_test.go
  pkg/tests/end_to_end_tests/drop_test.go
  pkg/tests/end_to_end_tests/ha_single_promscale_test.go
Labels: Performance

#1804 Vacuum compressed chunks missing stats
  CHANGELOG.md
  docs/vacuum.md
  pkg/tests/end_to_end_tests/vacuum_test.go
  pkg/vacuum/vacuum.go
Labels: epic/autovacuum-improvements
