Repository timescale/promscale, pull requests merged in 2022-05, with the labels that each got.

#1325 Filter on jsonb hash so planner can use index
  pkg/jaeger/query/get_operations.go
  pkg/jaeger/query/trace_query.go
Labels: Performance

#1365 Reformat markdown files with mdox
  README.md
  docs/configuring_prometheus.md
  docs/docker.md
  docs/downsampling.md
  docs/metric_deletion_and_retention.md
  docs/multi_tenancy.md
  docs/sql_permissions.md
  docs/tracing.md
Labels: Bug, Documentation

#1366 Use glob filter for mbox instead of find
  Makefile
Labels: Improvement

#1370 Manage stopping of ingest components
  go.mod
  pkg/pgmodel/ingestor/dispatcher.go
  pkg/pgmodel/ingestor/ingestor.go
  pkg/pgmodel/ingestor/ingestor_test.go
  pkg/rules/rules.go
Labels: Bug

#1378 Add HEAD and OPTIONS on healthz
  pkg/api/router.go
Labels: Bug

#1381 Support slices in traces attributes
  pkg/jaeger/query/trace_scan.go
  pkg/tests/end_to_end_tests/dataset_traces_test.go
Labels: Bug
